stages:
  - security

semgrep-sast:
  image: python:3.10
  stage: security
  before_script:
    - pip install semgrep
  script:
    - semgrep --config=custom-rules.yaml --json --output=semgrep-results.json
  artifacts:
    paths:
      - semgrep-results.json
