name: Semgrep SAST Scan

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto --json --output=semgrep-results.json

      - name: Print results
        run: cat semgrep-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json

